name: "SQL MCP Server"

services:
  server-mcp:
    image: sql-mcp-server:latest
    container_name: sql-mcp-server
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - sql-mcp-server
    env_file:
      - .env
    environment:
      DATABASE_ABSOLUTE_PATH: /app/database/data/sample.db
    restart: unless-stopped
    ports:
      - 8080:8080